global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

api:
  dashboard: true
  debug: false
  insecure: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

  # konfigurasi menggunakan domain
  # serversTransport:
  #   insecureSkipVerify: true

  # certificatesResolvers:
  #   cloudflare:
  #     acme:
  #       email: 
  #       storage: /ssl-certs/acme.json
  #       caServer: https://acme-v02.api.letsencrypt.org/directory
  #       dnsChallenge:
  #         provider: cloudflare
  #         resolvers:
  #         - "1.1.1.1:53"
  #         - "8.8.8.8:53"
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    exposedByDefault: false
    # swarmMode: false
  file:
    directory: /etc/traefik
    watch: true
