tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/selfsigned.crt
        keyFile: /certs/selfsigned.key
  certificates:
    - certFile: /certs/selfsigned.crt
      keyFile: /certs/selfsigned.key
      stores:
        - default